version: '3'

services:

  web:
    build: .
    command: sh -c "cd /usr/src/app && python manage.py runserver 0.0.0.0:8000 & cd /usr/src/app/frontend && npm start & tail -f /dev/null"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASES_URL}
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis
    ports:
      - "6379"
